# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Poetry tool
      uses: abatilo/actions-poetry@v2
    - name: Install the project dependencies
      run: poetry install
    - name: Linting
      run: poetry run flake8 src tests
    - name: Static analysis
      run: poetry run mypy src tests
    - name: Testing
      run: poetry run pytest -v
